server:
  port: 8081
  servlet:
    context-path: /luckymoney

# Must have a space between key and value
limit:
  minMoney: 2
  maxMoney: 999
  description: The minimum amount is ${limit.minMoney}, while the maxism amount is ${limit.maxMoney}